### ISSUE TITLE
Can't clone repositories

### ISSUE THREAD

**Issue by WiBla** [Rikette/ezblih#2]
Hello,

I just made a fresh install of ezblih on my Windows 10 machine and it seems like the cloning command doesn't work.

The error I get when I try to clone a repository is :
```
Cloning into 'test'...

Host key verification failed.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I created the `test` repo using EZ Blih so this shouldn't be a config error (both SSH key and logins are correct).

---
EZ Blih V `1.2.4`
Node V `8.12.0`
NPM V `6.4.1`

**Comment by Hinara** [comment]
That's seems to be unrelated to ezblih
Try to ssh blih with `ssh git@git.epitech.eu`
If you don't get a valid prompt that's your private key is invalid or your public key is not on BLIH's server

**Comment by WiBla** [comment]
I just re-tested everything today without making any changes to my config and it seems that the `clone` command now works 🤷‍♀ 
I guess this was a temporary issue with blih's server 🤔

Closing this issue as it clearly isn't ezblih's fault.
Thanks for your help!
